In [1]:
import torch

the equation is y = x**2

In [5]:
x = torch.tensor(4.0,requires_grad=True)

In [6]:
x

tensor(4., requires_grad=True)

In [7]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [9]:
# Back Propagation, y = 2*x
y.backward()

In [10]:
print(x.grad)

tensor(8.)


In [27]:
lst = [[2.,3.,1.],[4.,5.,3.],[6.,7.,4.]]
torch_input = torch.tensor(lst,requires_grad=True)

In [28]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [6., 7., 4.]], requires_grad=True)

In [29]:
# y = x**3 + x**2
# y = 3x**2 + 2x
y = torch_input**3 + torch_input**2

In [30]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [252., 392.,  80.]], grad_fn=<AddBackward0>)

In [31]:
z = y.sum()

In [32]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [33]:
z.backward()

In [35]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [120., 161.,  56.]])