In [1]:
import torch

In [2]:
import numpy as np

In [3]:
lst = [3,4,5,6,7,8,9,10,11,12,13]
arr = np.array(lst)

In [4]:
tensors = torch.from_numpy(arr)
tensors

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=torch.int32)

In [5]:
# indexing is similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [6]:
tensors[1:8]

tensor([ 4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [7]:
# disadvantage of from_numpy is that the array and the tensor use the same memory location
tensors[3] = 100

In [9]:
arr
# The value of the arr is also changed

array([  3,   4,   5, 100,   7,   8,   9,  10,  11,  12,  13])

In [10]:
# Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100,   7,   8,   9,  10,  11,  12,  13],
       dtype=torch.int32)

In [11]:
# Now
tensor_arr[3] = 200
print(arr)
print(tensor_arr)

[  3   4   5 100   7   8   9  10  11  12  13]
tensor([  3,   4,   5, 200,   7,   8,   9,  10,  11,  12,  13],
       dtype=torch.int32)


In [13]:
# zeroes and ones just like numpy arrays
torch.zeros(2,3,dtype=float)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [14]:
torch.ones(2,3,dtype=float)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
# Arithmetic Operations --------------------------------
a= torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

print(a+b)

tensor([5., 7., 9.])


In [16]:
torch.add(a,b)

tensor([5., 7., 9.])

In [17]:
c = torch.zeros(3)

In [18]:
torch.add(a,b,out=c)

tensor([5., 7., 9.])

In [19]:
c

tensor([5., 7., 9.])

In [21]:
# some other operations --------------------------------

a = torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

print(a-b)
torch.sub(a,b)

tensor([-3., -3., -3.])


tensor([-3., -3., -3.])

In [22]:
torch.add(a,b).sum()

tensor(21.)

In [23]:
# Dot product --------------------------------

x = torch.tensor([1,2,3],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

x.mul(y)

tensor([ 4., 10., 18.])

In [24]:
x.dot(y)

tensor(32.)

In [26]:
# Matrix Multiplication

x = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
y = torch.tensor([[7,8],[9,10],[11,12]],dtype=torch.float)

torch.mm(x,y) # or torch.matmul(x,y)

# Tensors and Variables --------------------------------


tensor([[ 58.,  64.],
        [139., 154.]])

In [27]:
torch.matmul(x,y) # or torch.mat

tensor([[ 58.,  64.],
        [139., 154.]])

In [28]:
x@y

tensor([[ 58.,  64.],
        [139., 154.]])